#!/bin/bash
#   CURRENT=`pwd`
#   echo ${CURRENT##*.}
#   echo ${PWD##*.}
if [[ $# -le 0 ]] ; then
   program=${PWD##*.}
else
   program=$1
fi
echo "The output files will be generated by program: $program"
for i in {0..20}
do
   echo "Generating file output$i.txt"
   cp input$i.txt input.txt
   ./$program
   mv output.txt output$i.txt
   rm -rf input.txt
done
